### ISSUE TITLE
Load and Dump safely by default

### ISSUE THREAD

**Issue by pradyunsg** [emre/kaptan#43]
As I see it, safe behaviour should be default. PyYAML got that wrong. It would be nice if kaptan doesn't make the same mistake.

**Comment by pradyunsg** [comment]
Bump.

**Comment by tony** [comment]
Can you be more specific? What's the current behavior, and what you expect to see?

**Comment by pradyunsg** [comment]
Use `yaml.safe_load` instead of `yaml.load`.

(sorry for terseness, short on time)

**Comment by tony** [comment]
Understood. I will have to see if it could potentially functionality downstream or not.  

> Note that the ability to construct an arbitrary Python object may be dangerous if you receive a YAML document from an untrusted source such as the Internet. The function yaml.safe_load limits this ability to simple Python objects like integers or lists.

It seems intention of it being there is for security purposes. If that is the case, it makes sense that overriding it is done explicitly.

Is there any more information you have to add?   pyyaml makes it sound like arbitrary code could run explicitly downstream if safe_load is done by default.

**Comment by pradyunsg** [comment]
If safe load is _not_ done, it's a security risk as arbitrary code may be
run... Not the other way round.

**Comment by emre** [comment]
Agreed that we should use safer option by default.

**Comment by tony** [comment]
Sounds good

@pradyunsg Would you like to make a PR?

**Comment by pradyunsg** [comment]
I shall in a few hours. If I don't, feel free to do it yourself. :smile:

**Comment by pradyunsg** [comment]
There you go.
