### ISSUE TITLE
Kaptan breaks environments needing newer PyYaml

### ISSUE THREAD

**Issue by vmalloc** [emre/kaptan#89]
PyYAML released version 4.1, fixing many issues including 3.7 support.
Unfortunately once a project is indirectly dependent on Kaptan (like through `tmuxp` in my case) - installation breaks because it conflicts with its requirement (==3.12).

Is there any chance to release a fix requiring `<5.0`?

**Comment by tony** [comment]
@vmalloc Yep. We can do an emergency release to pin our yaml dependency. Then a second one to upgrade pyyaml support.

You can PR the pyyaml lock if you want.

**Comment by vmalloc** [comment]
IMO the problem is that your version *is* currently pinned, which prevents projects from using 4.1 and working with Python 3.7...

**Comment by tony** [comment]
@vmalloc (This is news to me. Sorry for not being totally up to date on it, been busy lately)

I don't know the fully backstory. Can you fill me in on the version compliance issue between python and pyyaml versions?

If I knew that, I could make it so setup.py picks a different pyyaml version depending on the interpreter used. Similar to what I did here: https://github.com/fabtools/fabtools/commit/1746a813607d314d645e92d3dc21a7a923f94ede#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by vmalloc** [comment]
I'm not 100% up to speed either. All I know is that PyYAML didn't compile on 3.7 so far. Then they went ahead and released a fix for that along with a ton of other fixes and bumped it to 4.1. This means that 3.7 requires 4.1...

Given 3.7 is in the wild now, I don't see a reason to require 4.1 conditionally. I say just bump it to `<5` (to prevent future breakage when 5 lands) and see that it works. If it does - release it. 

AFAIK 4.1 is backwards compatible, with the exception of 3.3, which is broken for many other reasons so people don't use it anymore...

**Comment by tony** [comment]
Something happened here: https://travis-ci.org/emre/kaptan/jobs/397149540

I think it's safe to drop 3.3 support, yes

**Comment by vmalloc** [comment]
My guess about that test is that they now automatically encode unicode keys in some cases (perhaps when they're a subset of ASCII?)

Not sure what `safe` means but it's worth a closer look

**Comment by vmalloc** [comment]
To my understanding `safe` should quote Pythonic objects other than strings, so passing in a unicode string doesn't make sense as a test case. Not 100% sure though.

**Comment by tony** [comment]
@vmalloc it looks like they pulled 4.1 from pypi:

https://pypi.org/project/PyYAML/#history

```
kaptan-x9ExaD0b ❯ pip install pyyaml==4.1
Collecting pyyaml==4.1
  Could not find a version that satisfies the requirement pyyaml==4.1 (from versions: 3.10, 3.11, 3.12, 4.2b1, 4.2b2)
No matching distribution found for pyyaml==4.1
```

**Comment by vmalloc** [comment]
@tony yes, I just read the issue in which they summarize the situation of PyYAML. Sounds like it's not going to be released for some time now, and there's a big set of problems plaguing it. For example, they can't even re-build the already released version (3.12), and they don't have any estimate.

I think the right thing to do is switch away from it. I'm going to move my projects to `ruaml.yaml`, as it seems right now...

**Comment by tony** [comment]
@vmalloc Is it better now that pyyaml 3.13 is released?

**Comment by vmalloc** [comment]
From a quick experimentation it looks to be working. I haven't done more extensive tests but looks like you can pin it to `<4`...

**Comment by jpeyret** [comment]
FWIW, Github sent me this nice message on Jan 4th.

`Known high severity security vulnerability detected in pyyaml < 4.2b1`

Now, I just cloned kaptan, then re-installed PyYAML.  Which meant that kaptan would not work.

So I updated the requirements from my recent YAML.

	--- a/requirements/base.txt
	+++ b/requirements/base.txt
	@@ -1 +1 @@
	-PyYAML>=3.13,<4
	+PyYAML==5.1

and ran pytest, which was just A-OK.  Looks like PyYAML has fixed whatever they needed to fix.

	=========================================================================== test session starts ============================================================================
	platform darwin -- Python 3.6.8, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
	rootdir: /Users/jluc/kds2/wk/clones/kaptan
	plugins: cov-2.6.1, celery-4.3.0
	collected 21 items

	test_kaptan.py ........s............                                                                                                                                 [100%]

	=================================================================== 20 passed, 1 skipped in 0.08 seconds ==

**Comment by tony** [comment]
@vmalloc Thanks for the report. Sorry for the pyyaml / pinning issues.

I believe that 8aee1dbcc98feca8a6069ea44b676ef6557a50bf / 0.5.12 addresses this issue (hopefully for the future). If this issue still persists / comes up again please feel free to reopen.
